### ISSUE TITLE
SpaceCenter.warp_to causes "Array index is out of range"

### ISSUE THREAD

**Issue by TeWu** [krpc/krpc#169] opened 2015-09-27 14:39 UTC
`SpaceCenter`'s method `wrap_to` raises `krpc.error.RPCError: Array index is out of range.`.
I guess this happens when too big warp factor is used, because when this method is called with `max_rails_rate` parameter set to `10000` it is executed properly.
I also guess this is kRPC server side bug, because it manifest itself in [Ruby client library](https://github.com/TeWu/krpc-rb) as well.

Here, I'm using kRPC version 0.1.11 (downloaded 27 Sep 2015 from [kerbalstuff](https://kerbalstuff.com/mod/636/kRPC:%20Remote%20Procedure%20Call%20Server)):
```shell
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import krpc
>>> cl = krpc.connect()
>>> sc = cl.space_center
>>> v  = sc.active_vessel
>>> o  = v.orbit
>>> o.periapsis_altitude
1642162.5121806911
>>> o.apoapsis_altitude
31015418.759828445
>>> o.body.name
u'Kerbin'
>>> o.time_to_periapsis
414.7778435177752
>>> o.time_to_apoapsis
116798.49923769127
>>> sc.warp_to(sc.ut + o.time_to_apoapsis)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "krpc/client.py", line 122, in _invoke
    raise RPCError(response.error)
krpc.error.RPCError: Array index is out of range.
```

**Comment by djungelorm** [comment] 2016-02-25 05:37
Sorry this took me so long to get around to... The issue was caused by trying to warp at more than the maximum rate when the target UT is sufficiently far in the future. Fixed in the upcoming 0.2.2.

**Closed** 2016-02-25 06:09 UTC
Labels: bug, services-spacecenter
