### ISSUE TITLE
Resources amounts & max not working

### ISSUE THREAD

**Issue by ThePerkinrex** [krpc/krpc#545] opened 2018-10-12 11:48 UTC
the`krpc_SpaceCenter_Resources_Amount` & `krpc_SpaceCenter_Resources_Max` don't work and just give `0.0` as an output.

I have attached a file with the example code
[krpc_res_test.zip](https://github.com/krpc/krpc-arduino/files/2472899/krpc_res_test.zip)

**Comment by djungelorm** [comment] 2019-09-23 19:01
Sorry for the very slow response.

I'm not able to reproduce the error. Do you have a craft file that causes this issue, or save file with the craft in a situation where this bug occurs?

**Comment by ThePerkinrex** [comment] 2019-09-24 20:35
I'm sorry, this was so long ago I don't remember what the craft was

I don't have anything more, because I switched to using a c++ client on the computer which connects to krpc using the lib and to the arduino using serial.
The problem was basically the one said in main comment. I don't remember anything more. I'm really sorry

**Comment by djungelorm** [comment] 2019-09-24 22:31
No worries, thanks for getting back to me. I'll just close this then as I can't reproduce it.

**Closed by djungelorm** 2019-09-24 22:31 UTC
Labels: bug, service:space-center
