### ISSUE TITLE
Waiting for events in a way that does not require expensive loops.

### ISSUE THREAD

**Issue by dewiniaid** [krpc/krpc#316] opened 2016-07-23 17:33 UTC
Realtime control of craft in kRPC is currently fairly expensive from both the client's perspective and from (if the RPC count is high enough) KSP's perspective.  For instance, a method that changes autopilot settings (e.g. a pitch program) based on current state (e.g. altitude) has no means to limit itself to once every physics frame and instead executes as fast possible.  Additionally, waiting for any sort of condition (e.g. a particular altitude to be reached) currently can't be done (to my knowledge) any more efficiently than something like:

``` python
altitude = conn.add_stream(getattr, conn.space_center.active_vessel.flight(), altitude)
while altitude() < 80000: pass
```

At the simplest level, an RPC that blocks until the next physics frame (say, `conn.wait()`) would be a useful way to improve performance in these cases.   A primitive event system could also be useful, particularly if integrated into something like Python's `asyncio` or similar mechanisms in other languages.

The rest of this is a rough-draft idea of what events can look like.  **All examples are using the Python client**
## Events

There's two ways events can be implemented: either purely in the client library or a hybrid approach.
### Pure Client

The pure-client approach is already mostly doable in the Python client -- it'd just require a way to associate a callback with `krpc.stream.Stream` that is called as part of its update() method.  From there, the callback can implement whatever glue is needed to attach to asyncio/wake up a thread/etc.

This doesn't allow for super-efficient cases of things like "wait until altitude > 10000" however, though it helps.
### Hybrid

As Pure Client, but using an `Event` class with some support for conditions.
#### Adding Events

In the below methods, _callback_ is a function that is called whenever the event is triggered and recieves the event as its sole argument. _once_, if True, removes the event after the first time it triggers.  (The callback function will not be notified of the removal in this case).

All events return an instance of `Event` or one of its subclasses.

**Client.add_unity_event(_event_name_, ..., _callback_, _once_)**

Adds a client event that is triggered when the corresponding Unity(-esque) event is triggered.

**Client.add_stream_event(_stream_, _callback_, _once_)**

Adds a client event that triggers when the value of _stream_ changes.

**Client.add_condition_event(_stream_, _operator_, _value_, _callback_, _once_)**

Adds a client event that triggers when the value of _stream_ satisfies the specified condition.  If the condition is already satisfied, the event is triggered immediately.

Once the condition is satisfied, the event will not trigger again until the condition returns to being False and then becomes True again.

_operator_ may be any of the logical comparison operators {`<`,`<=`, `==`, `>=`, `>`, `!=`}.  `=` and `<>` should also be accepted as aliases to `==` and `!=`.

Checks for condition events happen at the start of each physics frame.  (TODO: There should probably be some other checks for non-physics places like the VAB).
#### Event class

These methods should be pure-client, all attributes should be set in the message that notifies clients of the event.  Alternatively to these methods (which attempt to mimic streams), mimic the Python [asyncio.Future API](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Future) (but that doesn't allow for recurring events)

**Event.remove()**

Removes this event.

**Event.removed()**

Returns True if the event was removed (possibly due to being a no-longer-valid event, such as an event looking at active vessel after a scene change).  If this is True during the event callback, the event's value should be ignored.

**Event.value()**

Returns the value of the underlying stream object or relevant data based on the Unity event, if applicable.

Raises a relevant exception if an error occurred while handling the event or the event was cancelled.

**Comment by dewiniaid** [comment] 2016-07-26 02:28
Didn't notice #300 until now, mentioning it here to tag both issues.

**Comment by djungelorm** [comment] 2016-07-26 03:43
I like this idea a lot! The hybrid approach sounds best, another pro of which is that it moves some of the complexity of implementation into the server (for which there is one implementation compared to the 7 or so client libraries).

Regarding the interface of the Event class, I think it would be better to follow the interface used by threading.Event? https://docs.python.org/2/library/threading.html#event-objects And then for the other languages (C++, Java etc.) we can add similar event classes following the same convention that the standard libraries in those languages use. We could always provide more complex abstractions like that provided by asyncio.Future on top of this lower level Event class.

In terms of implementing the server -> client event notification, this could be done efficiently by using the current stream architecture, due to the following points (this is specific to the Python client, but other clients are similar)

- The client has a separate 'stream update' thread that waits for stream update messages from the server. It does this efficiently [using a select call](https://github.com/krpc/krpc/blob/master/client/python/krpc/connection.py#L62)  (although that 0.01 second timeout could be made larger... not sure why I set it to such a short timeout)
- Stream update messages do not need to include values for all of the streams, just those whose values have changed. So, for each event we could create a stream on the server that returns a boolean value indicating whether the event has fired. The value of this stream will be False until the event occurs at which point it becomes True. This would require a single update message when the stream is created, and then one message when the event occurs.
- The server collects stream update messages from the same physics tick into a single stream update message, so the event notification would be automatically bundled up with all the other stream updates.

On the server side, some changes will be needed to make updating the value of the event stream efficient. Currently the only way you could do it is by actively polling the event - far from ideal! This is because currently a stream value is updated by simply invoking the RPC described by the request message attached to the stream. We'd need a new type of stream where the handler for a Unity event or whatever can inform the server of a new value for the stream to be sent in the next stream update.

If you like I can put together a server with these stream changes so you can hack on the Python client?

(I've also closed #300, as it has no discussion and is a duplicate of this)

**Comment by dewiniaid** [comment] 2016-07-26 04:42
> Regarding the interface of the Event class, I think it would be better to follow the interface used by threading.Event? https://docs.python.org/2/library/threading.html#event-objects And then for the other languages (C++, Java etc.) we can add similar event classes following the same convention that the standard libraries in those languages use. We could always provide more complex abstractions like that provided by asyncio.Future on top of this lower level Event class.

I didn't realize that `asyncio.Future` and `concurrent.futures.Future` were Python 3-only, so that slightly changes things.  That said:

I think the asyncio.Future semantics are a bit easier to work with from a user perspective.  CPython tends to not handle threading particularly well (due to the GIL), and a client may not necessarily want to _block_ on an event.  So actually blocking while waiting for an event is less than ideal vs. a callback-based (PR #320 has a fairly simple prototype implementation)

Also, I _think_ it'd be easier to mimic threading.Event on top of asyncio.Future than the reverse.

> Stream update messages do not need to include values for all of the streams, just those whose values have changed. So, for each event we could create a stream on the server that returns a boolean value indicating whether the event has fired. The value of this stream will be False until the event occurs at which point it becomes True. This would require a single update message when the stream is created, and then one message when the event occurs.

I think for simple "Tell me when a value changes" events, the existing Stream mechanism makes more sense.  If I want to be told whenever e.g. the game scene changes, it's not particularly efficient to tell me it changed but then make me ask what the new scene is.

For conditional events, a True vs False stream that triggers works.  Alternatively, if it's more efficient, there could be a single streamed integer corresponding to up to 64 active events.  I'd say save that level of optimization for an even more future version, though.

**Comment by djungelorm** [comment] 2016-07-26 05:04
Fair enough, tbh I don't have any experience of the asyncio library, just what's in the python 2 `threading` package.

For the more events that return a value, we can still use streams. We can notify the Python event/future when the stream update message is received with the new value - it doesn't have to have a boolean value. I overlooked this above, sorry!

And nice idea on the encoding, but yeah lets leave that for a future version.

**Comment by dewiniaid** [comment] 2016-07-27 01:52
Futures in a nutshell (the exact implementation may vary) are:

1. You call a function that may take some time to fully complete.
2. That function returns a Future
3. You `yield` that Future to upstream code, which ultimately ends up being an event loop.  This suspends execution of your function at the point the yield happened.
4. At some later point, the Future is resolved and has either an exception or a value assigned to it.
5. If the future raised an exception, that exception is raised in your code at the point the `yield` occured.  Otherwise, the future's result is the return value from yield.

They're a nice abstraction for handling things like task queues and concurrent code, whether that code is running in a single thread (where `yield` forms a sort of cooperative multitasking), multiple threads, or even multiple processes.  They're also sometimes referred to as `Promises` in other languages.

In asyncio's case, most of the callback mess is abstracted out; when an appropriately-designed function yields a future the event loop will automatically add a callback that more or less is "resume execution of the function until it yields again or returns"

But that's enough cluttering up the actual issue.

**Closed** 2017-10-03 18:27 UTC
Labels: enhancement, server:api
